name:                projReducer
version:             0.1.0.0
github:              "fyu/projReducer"
license:             BSD3
author:              "fyu"
maintainer:          "frank_yzg@outlook.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fyu/projReducer#readme>

dependencies:
- base >= 4.7 && < 5
- text == 1.2.3.1
- process == 1.6.5.0
- containers == 0.6.0.1
- transformers == 0.5.6.2
- directory == 1.3.3.0
- makefile == 1.1.0.0
- mtl == 2.2.2
- language-bash == 0.9.2

library:
  source-dirs: src

executables:
  projReducer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projReducer

tests:
  projReducer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - projReducer
